version: '3.8'
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=shoes_store
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/shoe-store:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/shoes_store
volumes:
  pg_data: