name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Kirim file docker-compose ke EC2
      - name: Copy docker-compose.prod.yaml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "docker-compose.prod.yaml"
          target: "~/shoe-store"

      # Deploy aplikasi
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/shoe-store

            # Rename file compose
            mv docker-compose.prod.yaml docker-compose.yml

            # Setup environment variables
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env

            # Jalankan docker-compose
            docker-compose up -d

            # Tunggu database siap
            for i in {1..12}; do
              docker-compose exec -T postgres pg_isready -U ${{ secrets.DB_USER }} && break
              sleep 5
            done

            # Jalankan migrasi Prisma
            docker-compose exec -T app npx prisma migrate deploy

            # Debug container
            docker-compose ps
