name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:  # Memungkinkan trigger manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/shoe-store
            docker-compose down
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            docker-compose up -d
            sleep 10  # Beri waktu untuk database startup
            docker-compose exec app npx prisma migrate deploy
          envs: DOCKER_IMAGE
          sync: true
          sync_options: --delete