name: Deploy to EC2

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/shoe-store
  SSH_HOST: ${{ secrets.AWS_EC2_IP }}
  SSH_USER: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/shoe-store
            docker-compose down
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            docker-compose up -d
            docker-compose exec app npx prisma migrate deploy
