name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 1. Buat direktori tujuan
            mkdir -p ~/shoe-store
            cd ~/shoe-store
            
            # 2. Sync file menggunakan mekanisme resmi
            echo "File yang di-sync:"
            ls -la
            
            # 3. Validasi file compose
            if [ ! -f "docker-compose.prod.yaml" ]; then
              echo "Error: File docker-compose.prod.yaml tidak ada!"
              echo "Isi direktori:"
              ls -la
              exit 1
            fi
            
            # 4. Rename file
            mv docker-compose.prod.yaml docker-compose.yml
            
            # 5. Setup environment variables
            echo "DB_USER=$DB_USER" > .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            
            # 6. Jalankan docker-compose
            docker-compose -f docker-compose.yml up -d
            
            # 7. Tunggu database siap
            for i in {1..12}; do
              docker-compose exec postgres pg_isready -U $DB_USER && break
              sleep 5
            done
            
            # 8. Jalankan migrasi
            docker-compose exec app npx prisma migrate deploy
          envs: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          sync: true
          sync_options: |
            --include=docker-compose.prod.yaml
            --exclude=*