name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            mkdir -p ~/shoe-store
            cd ~/shoe-store
            # Copy file docker-compose dari repo ke server
            cp /github/workspace/docker-compose.prod.yaml .
            # Rename file agar dikenali docker-compose
            mv docker-compose.prod.yaml docker-compose.yaml
            echo "DB_USER=$DB_USER" > .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/shoe-store:latest
            docker-compose up -d
            sleep 10
            docker-compose exec app npx prisma migrate deploy
          envs: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          sync: true
          sync_options: |
            --exclude=.git
            --exclude=node_modules