name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            mkdir -p ~/shoe-store
            cd ~/shoe-store
            
            # 1. Copy file langsung dari repo
            cp $GITHUB_WORKSPACE/docker-compose.prod.yaml .
            
            # 2. Gunakan nama file yang benar
            mv docker-compose.prod.yaml docker-compose.yml
            
            # 3. Setup environment
            echo "DB_USER=$DB_USER" > .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            
            # 4. Jalankan docker dengan config eksplisit
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
            
            # 5. Tunggu database ready
            sleep 15
            docker-compose -f docker-compose.yml exec app npx prisma migrate deploy
          envs: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GITHUB_WORKSPACE=/github/workspace
          sync: true